### ISSUE TITLE
Tổng hợp các từ điển dịch thuật ngữ

### ISSUE THREAD

**Issue by ooker777** [thuatngu/STEM#1]
Chào bạn, mình cũng có sưu tập một các từ điển thuật ngữ, có thể nó sẽ giúp ích cho bạn :smiley: [https://drive.google.com/drive/folders/0BzfbMzZB7mgyNnpiV1lvQzBpVjg?usp=sharing][1]  

Ngoài ra cũng có một số trang web khác:
- [Việt Hóa Thuật Ngữ][2]  
- [thuatngu][3]  

[1]: https://drive.google.com/drive/folders/0BzfbMzZB7mgyNnpiV1lvQzBpVjg?usp=sharing
[2]: http://thuatngu.tieng-viet.org/
[3]: https://github.com/thuatngu

**Comment by doanminhdang** [comment]
Cảm ơn @ooker777, bộ sưu tập của bạn ở Drive hình như chỉ gồm ebooks, nếu bạn có file từ điển thuật ngữ nào thì chỉ cho mình nhé. Trang thuatngu.tieng-viet.org cũng là một cố gắng đáng quý trong việc xây dựng thuật ngữ, tác giả ở đó nếu tham khảo được sách "Danh từ khoa học" của Hoàng Xuân Hãn thì chắc sẽ làm có hệ thống hơn.

**Comment by ooker777** [comment]
Ủa, trong đó toàn là file thuật ngữ Anh - Việt không mà bạn?

Mình cũng không kiếm ra cuốn đó, bạn có không gửi cho mình được không? Mình cảm ơn.

**Comment by doanminhdang** [comment]
@ooker777 Quyển nào trong thư mục GDrive của bạn là thuật ngữ thì bạn cho tên và link để mình xem lại, còn mình xem nhiều quyển trong đó chỉ là ebook, các ebook đó là sách, giống kiểu như giáo trình, chứ không phải thuật ngữ.
Ở đây có file sách "Danh từ khoa học": https://rosetta.vn/translate/danh-tu-khoa-hoc-sach-hoang-xuan-han/

**Comment by ooker777** [comment]
Sặc, mình cho lộn link :rofl: 
https://drive.google.com/open?id=0BzfbMzZB7mgyZmxfQ0VmT3lnZzg

Mình mới lướt qua website của bạn, thì chỉ biết nói là: "ôi tôi gõ đúng cửa rồi" :)). Sau bao năm trăn trở :)). Mình có ôm ấp một dự án để mọi người thống nhất thuật ngữ cho đúng, hoạt động như kiểu reddit hay Stack Exchange, nhưng giờ chưa có thời gian :))

**Comment by doanminhdang** [comment]
@ooker777 Bạn sưu tầm được nhiều tài liệu thuật ngữ tốt quá, cảm ơn bạn chia sẻ rất nhiều!

Mình cũng đang bỏ công để số hóa từ điển chuyên ngành, nhằm tạo dữ liệu thuật ngữ cho tiện sử dụng. Mô hình mình đưa ra ở đây: https://rosetta.vn/translate/xay-dung-thuat-ngu-va-dung-trong-phan-mem-ho-tro-nhom-dich/

Bạn có muốn tham gia làm cùng mình không? Việc trước mắt là convert / OCR và số hóa nguồn dữ liệu phong phú mà bạn đã tập hợp được. Mình sẽ gửi email trao đổi thêm nhé (mình gửi vào email hiện ra trên profile Github của bạn).

**Comment by ooker777** [comment]
Ồ, bạn làm chu đáo quá. Hẳn là phải nhiệt tình lắm.

Ừ, mình cũng muốn xây dựng một cơ sở dữ liệu như thế, nhưng bây giờ bắt tay vào làm thì kẹt quá. Có lẽ là hết năm mới tính tiếp được. Nhưng bàn ý tưởng thì không sao.

Email của mình là lyminhnhat911@gmail.com. Mình cũng đã phân loại và OCR kha khá từ điển trong đó. Vấn đề bản quyền cũng rất cần được quan tâm.

Để xưng hô cho tiện, thì mình sinh năm 92.

**Comment by quachnamth** [comment]
> Cảm ơn @ooker777, bộ sưu tập của bạn ở Drive hình như chỉ gồm ebooks, nếu bạn có file từ điển thuật ngữ nào thì chỉ cho mình nhé. Trang thuatngu.tieng-viet.org cũng là một cố gắng đáng quý trong việc xây dựng thuật ngữ, tác giả ở đó nếu tham khảo được sách "Danh từ khoa học" của Hoàng Xuân Hãn thì chắc sẽ làm có hệ thống hơn.

Xin chào anh, tôi rất vui khi nhận được thông tin anh làm bên số hóa các từ điển. tôi mong muốn được hợp tác cùng anh và trao đổi thêm về các dự án.
